- name: Creating /root/.ssh directory
  become: true
  file: path="/root/.ssh" mode="700" state=directory

- name: Creating /home/vagrant/.ssh directory
  become: true
  file: path="/home/vagrant/.ssh" mode="700" state=directory

- name: Copying id_rsa keys
  become: true
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - {src: '~/.ssh/id_rsa.pub', dest: '/root/.ssh/authorized_keys', mode: '0600'}
    - {src: '~/.ssh/id_rsa.pub', dest: '/home/vagrant/.ssh/authorized_keys', mode: '0600'}
